server:
  port: 10086
  servlet:
    context-path: /api

spring:
  application:
    name: xueBuTong-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306

